import java.io.File

plugins {
    id("education.cccp.bakery") version "0.1.4"
    id("cheroliv.com.workspace.pilot") version "0.0.0"
}

val officePath: String = System.getenv("OFFICE_PATH") ?: "/home/cheroliv/workspace/office"
val workspaceRoot = File(System.getenv("HOME") ?: "/home/cheroliv").resolve("workspace")
val foundryDir = workspaceRoot.resolve("foundry/public")
val siteName: String = project.findProperty("siteName") as? String ?: "cheroliv.com"

// HACK: utiliser un chemin relatif depuis runner-gradle/ pour contourner le bug
// File.resolve(cheminAbsolu) dans le bakery plugin v0.1.4.
// Le plugin utilise File(File parent, String child) qui concatène avec les
// chemins absolus au lieu de les remplacer.
val siteConfigFile = file("$officePath/sites/$siteName/site.yml")
val relativeConfigPath = project.layout.projectDirectory.asFile
    .toPath()
    .relativize(siteConfigFile.toPath())
    .toString()

bakery {
    configPath.set(relativeConfigPath)
}

val dagLevels = mapOf(
    "graphify-gradle" to 0,
    "codebase-gradle" to 1,
    "bakery-gradle" to 2,
    "codex-gradle" to 2,
    "magic-stick" to 2,
    "planner-gradle" to 2,
    "plantuml-gradle" to 2,
    "quizz-benchmark-gradle" to 2,
    "quizz-benchmark-plugin" to 2,
    "readme-gradle" to 2,
    "slider-gradle" to 2,
    "training-gradle" to 2,
    "capsule-gradle" to 2,
    "runner-gradle" to 3,
    "waiter-plugin" to 2,
    "office-template" to 2,
    "jhipster-gradle-plugins" to 2,
    "notebook-gradle" to 2,
    "newpipe-gradle" to 2,
    "scripts" to 2,
    "site" to 2
)

val githubOrg = "cheroliv"
val pluginRepos = mapOf(
    "graphify-gradle" to "graphify-gradle",
    "codebase-gradle" to "codebase-gradle",
    "bakery-gradle" to "bakery-gradle",
    "codex-gradle" to "codex-gradle",
    "planner-gradle" to "planner-gradle",
    "plantuml-gradle" to "plantuml-gradle",
    "quizz-benchmark-gradle" to "quizz-benchmark-gradle",
    "readme-gradle" to "readme-gradle",
    "slider-gradle" to "slider-gradle",
    "training-gradle" to "training-gradle",
    "waiter-plugin" to "waiter-plugin",
    "jhipster-gradle-plugins" to "jhipster-gradle-plugins",
    "notebook-gradle" to "notebook-gradle",
    "newpipe-gradle" to "newpipe-gradle",
    "magic-stick" to "magic-stick",
    "runner-gradle" to "runner-gradle"
)

tasks.register("deployWorkspace") {
    group = "deploy"
    description = "Generates a provision.sh script to bootstrap a full workspace"

    val outputDir = project.layout.buildDirectory.dir("provision")
    val provisionScript = outputDir.map { it.file("provision.sh") }

    outputs.file(provisionScript)

    doLast {
        val dest = provisionScript.get().asFile
        dest.parentFile.mkdirs()
        dest.writeText(buildProvisionScript(dagLevels, pluginRepos))
        dest.setExecutable(true)

        println("Workspace provision script generated: ${dest.absolutePath}")
        println()
        println("To provision a workspace:")
        println("  chmod +x ${dest.absolutePath}")
        println("  ${dest.absolutePath} /path/to/workspace")
    }
}

fun buildProvisionScript(levels: Map<String, Int>, repos: Map<String, String>): String {
    val sb = StringBuilder()
    sb.appendLine("#!/usr/bin/env bash")
    sb.appendLine("# Runner - provision.sh - Bootstrap a full workspace from scratch")
    sb.appendLine("# Generated by: runner-gradle deployWorkspace")
    sb.appendLine()
    sb.appendLine("set -euo pipefail")
    sb.appendLine()
    sb.appendLine("WS=\${1:-\$(pwd)/workspace}")
    sb.appendLine("echo \"Provisioning workspace at \$WS\"")
    sb.appendLine("mkdir -p \"\$WS\"/{foundry/public,office,office/sites,office/pilotage,configuration,configuration/.agents,configuration/vision-archive,configuration/settings}")
    sb.appendLine()

    val byLevel = levels.entries
        .filter { repos.containsKey(it.key) }
        .groupBy({ it.value }, { it.key })
        .toSortedMap()

    for ((level, projects) in byLevel) {
        sb.appendLine("# --- N$level projects ---")
        for (project in projects) {
            val repo = repos[project]!!
            sb.appendLine("echo \"  Cloning $project (N$level)...\"")
            sb.appendLine("if [ ! -d \"\$WS/foundry/public/$project\" ]; then")
            sb.appendLine("    git clone --depth 1 https://github.com/$githubOrg/$repo.git \"\$WS/foundry/public/$project\" 2>/dev/null || true")
            sb.appendLine("fi")
        }
        sb.appendLine()
    }

    sb.appendLine("# Runner at workspace root symlink")
    sb.appendLine("ln -sf \"\$WS/foundry/public/runner-gradle/runner.sh\" \"\$WS/runner\" 2>/dev/null || true")
    sb.appendLine()
    sb.appendLine("echo \"Workspace provisioned.\"")
    sb.appendLine("echo \"Next steps:\"")
    sb.appendLine("echo \"  cd \$WS/foundry/public/runner-gradle && ./gradlew tasks --group runner\"")

    return sb.toString()
}

tasks.register("info") {
    group = "info"
    description = "Shows runner status: DAG levels, known plugins, workspace paths"

    doLast {
        println("============================================")
        println("  Runner v1.0 - N3 Orchestration")
        println("============================================")
        println()
        println("Workspace root : ${workspaceRoot.absolutePath}")
        println("Foundry (OSS)   : ${foundryDir.absolutePath}")
        println("Office          : $officePath")
        println("GitHub org      : $githubOrg")
        println()

        val byLevel = dagLevels.entries.groupBy({ it.value }, { it.key }).toSortedMap()
        println("-- DAG Registry (${dagLevels.size} projects) --")
        for ((level, projects) in byLevel) {
            println("  N$level: ${projects.joinToString(", ")}")
        }
        println()
        println("-- Runner Tasks --")
        println("  deployWorkspace          Generate workspace setup script")
        println("  verifyDagAcyclic         Verify DAG acyclic rule (via graphify-gradle N0)")
        println("  info                     This status display")
        println("  generateCompositeContext Delegate au plugin codebase-gradle (N1) — composite-context.json")
        println()
        println("-- Pilot Tasks (workspace-gradle N4) --")
        println("  verifyBoroughs           Validate metadata contracts for 11 boroughs (EPIC K-04)")
        println("  validateApiSchema        Validate OpenAPI 3.0 contract openapi.yaml")
    }
}

